config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :main_sliders
  end

  get 'set_language/english'

  get 'set_language/arabic'

  get 'homepage/index'
  root to: "homepage#index"
  devise_for :users, :skip => [:registrations]
  resources :cars do
    collection do
      get 'admin_car'
      patch 'admin_car_update'
      post "contact_submit" => "cars#contact_submit"
      delete "delete_image/:id" => "cars#delete_image"
    end
  end
  resources :members do
    collection do
      get 'admin_member'
      patch 'admin_member_update'
      patch  'member/edit/password/' => 'members#update_password'
      put  'member/edit/password/' => 'members#update_password'
    end
  end
  resources :dealers do
    collection do
      get 'admin_dealer'
      patch 'admin_dealer_update'
      patch  'dealer/edit/password/' => 'dealers#update_password'
      put  'dealer/edit/password/' => 'dealers#update_password'
    end
  end
  resources :makes, except: :show
  resources :models, except: :show
  resources :comfort_interiors, except: :show
  resources :interior_designs, except: :show
  resources :colors, except: :show
  resources :interior_colors, except: :show
  resources :safety_features, except: :show
  get 'admin', to: 'admin#index'

end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
	has_one :user, as: :meta, dependent: :destroy
	validates :gallery_name, :gallery_location, :street_name, :building_number, presence: true
  	accepts_nested_attributes_for :user
  	City = {
		"1" => "Amman",
		"2" => "Zarqa",
		"3" => "Irbid",
		"4" => "Aqaba",
		"5" => "as-Salt",
		"6" => "Ar Ramtha",
		"7" => "Madaba",
		"8" => "Mafraq",
		"9" => "Jerash",
		"10" => "Ma'an",
		"11" => "Tafilah",
		"12" => "Karak",
		"13" => "Ajloun"
	}
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]
  before_action :set_user , only: [:edit , :update_password]
  before_action :authenticate_access!, :only => [:index ,:edit, :update]
  before_action :authenticate_admin!,:only =>[:admin_member ,:index ,:destroy,:new,:create]
  # GET /dealers
  # GET /dealers.json
  def index
    @dealers = Dealer.all
  end

  # GET /dealers/1
  # GET /dealers/1.json
  def show
    @dealer_cars = Car.where(user_id: @dealer.user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @latest_cars = Car.last(10)
  end
  # GET /dealers/new
  def new
    @dealer = Dealer.new
    @dealer.build_user
  end

  # GET /dealers/1/edit
  def edit
  end

  # POST /dealers
  # POST /dealers.json
  def create
    @dealer = Dealer.new(dealer_params)
    respond_to do |format|
      if @dealer.save
        format.html { redirect_to @dealer, notice: 'Dealer was successfully created.' }
        format.json { render :show, status: :created, location: @dealer }
      else
        format.html { render :new }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/edit/password
  # PATCH/PUT
  def update_password
    respond_to do |format|
      if @user.update(dealer_params)
        format.html { redirect_to @user, notice: 'Dealer Password was successfully updated. Please login again' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_password }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dealers/1
  # PATCH/PUT /dealers/1.json
  def update
    respond_to do |format|
      if @dealer.update(dealer_params)
        format.html { redirect_to @dealer, notice: 'Dealer was successfully updated.' }
        format.json { render :show, status: :ok, location: @dealer }
      else
        byebug
        format.html { render :edit }
        format.json { render json: @dealer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dealers/1
  # DELETE /dealers/1.json
  def destroy
    @dealer.destroy
    respond_to do |format|
      format.html { redirect_to admin_dealer_dealers_path, notice: 'Dealer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def admin_dealer
    @dealers = Dealer.includes(:user).all.page(params[:page]).per_page(50)
  end
  def admin_dealer_update
    params['user'].keys.each do |id|
      @user = User.find(id.to_i)
      @user.update_attributes(admin_user_params(id))
    end
    if(authenticate_admin?)
      redirect_to(admin_dealer_dealers_path)
    else
      redirect_to root_path
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dealer
      @dealer = Dealer.find(params[:id])
    end

    def set_user
      user = User.find(current_user.id)
      @user = Dealer.find(user.meta_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dealer_params
      params.require(:dealer).permit(:page, :name, :mobile_number, :city, :gallery_name, :phone_number, :gallery_location, :street_name, :building_number, user_attributes: [ :id, :email, :password, :password_confirmation ])
    end
    def admin_user_params(id)
      params.require(:user).fetch(id).permit(:isadmin)
    end
    def authenticate_access!
      if user_signed_in?
        if(current_user.meta_id == Dealer.find(params[:id]).id || current_user.isadmin)
          true
        else
          if(@dealer)
            redirect_to @dealer
          else
            redirect_to :root
          end
        end
      else
        if(@dealer)
            redirect_to @dealer
          else
            redirect_to :root
          end
      end
    end
end

app/helpers/dealers_helper.rb
module DealersHelper
end

app/views/dealers/_edit_form.html.erb
<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dealer.errors.count, "error") %> prohibited this dealer from being saved:</h2>

      <ul>
      <% @dealer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <%= f.label t(:gallery_name) %>
      <%= f.text_field :gallery_name %>
    </div>
    <div class="field">
      <%= f.label t(:name) %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label t(:phone_number) %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label t(:mobile_number) %>
      <%= f.text_field :mobile_number %>
    </div>
    <div>
      <%= f.label t("city") %>
      <%= f.select :city, Dealer::City.map{ |s| [s[1] , s[0]] } %>
    </div>
    <div class="field">
      <%= f.label t(:gallery_location) %>
      <%= f.text_area :gallery_location %>
    </div>
    <div class="field">
      <%= f.label t(:street_name) %>
      <%= f.text_field :street_name %>
    </div>
    <div class="field">
      <%= f.label t(:building_number) %>
      <%= f.text_field :building_number %>
    </div>
  <div class="actions text-center">
    <%= f.submit t("update_information") , :class => 'button tiny buttoncustom' %>
  </div>
<% end %>

app/views/dealers/_edit_password_form.html.erb
<%= form_for @user , :url => url_for(:controller => 'dealers', :action => 'update_password') do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user do |u| %>
    <div class="col-lg-6">
      <%= u.label t(:password) %><br>
      <%= u.password_field :password %>
    </div>
    
    <div class="col-lg-6">
      <%= u.label t(:password_confirmation) %><br>
      <%= u.password_field :password_confirmation %>
    </div>
  <% end %>
  <div class="actions text-center">
    <%= f.submit t("update_password"), :class => 'button tiny buttoncustom' %>
  </div>
<% end %>

app/views/dealers/_form.html.erb
<%= form_for(@dealer) do |f| %>
  <% if @dealer.errors.any? %>
    <div data-alert class="alert-box warning">
      <ul>
      <% @dealer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="userInfo large-6 columns">
    <div class="field">
      <%= f.label t(:gallery_name) %>
      <%= f.text_field :gallery_name %>
    </div>
    <div class="field">
      <%= f.label t(:name) %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label t(:phone_number) %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label t(:mobile_number) %>
      <%= f.text_field :mobile_number %>
    </div>
    <div>
      <%= f.label t("city") %>
      <%= f.select :city, Dealer::City.map{ |s| [s[1] , s[0]] } %>
    </div>
    <div class="field">
      <%= f.label t(:gallery_location) %>
      <%= f.text_area :gallery_location %>
    </div>
    <div class="field">
      <%= f.label t(:street_name) %>
      <%= f.text_field :street_name %>
    </div>
    <div class="field">
      <%= f.label t(:building_number) %>
      <%= f.text_field :building_number %>
    </div>
  </div>
  <div class="userLoginInfo large-6 columns">
    <div class="innerUserLoginInfo">
      <%= f.fields_for :user do |u| %>
        <div class="field">      
          <%= u.label t(:email) %>
          <%= u.text_field :email %>
        </div>
        
        <div class="field">
          <%= u.label t(:password) %>
          <%= u.password_field :password %>
        </div>
        
        <div class="field">
          <%= u.label t(:password_confirmation) %>
          <%= u.password_field :password_confirmation %>
        </div>    
      <% end %>   
      <div class="actions text-center">
        <%= f.submit t("sign_in"), :class => 'button tiny buttoncustom createCar' %>
      </div>
    </div>
  </div>
  
<% end %>

app/views/dealers/admin_dealer.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>Dealer Admin Page</h2>
    </div>
  </div>
</section>
<section class="NewCar">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
    	<%= form_for :dealer, :url => admin_dealer_update_dealers_path, :html => { :method => :patch } do %>
		    <table>
		    	<thead>
				    <tr>
				      <th>Email</th>
				      <th>Name</th>
				      <th>Gallery Name</th>
				      <th>Last Sign in</th>
				      <th>admin</th>
				      <th colspan="2"></th>
				    </tr>
		  		</thead>
				  <tbody>
				    <% @dealers.each do |dealer| %>
				      <tr>
				        <td><%= dealer.user.email %></td>
				        <td><%= dealer.name %></td>
				        <td><%= dealer.gallery_name %></td>
				        <td><%= dealer.user.last_sign_in_at %></td>
				        <%= fields_for "user[]", dealer.user do |f| %>
				      		<td><%= f.check_box :isadmin %></td>
				      	<% end %>
				        <td><%= link_to 'Show', dealer %></td>
				        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
				        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				      </tr>
				    <% end %>
		  		</tbody>
				</table>
				<div class="actions">
			    <%= submit_tag %>
			  </div>
		  <% end %>
      <% if !(@dealers.total_pages == 1) %>
        <div class="pagerArea pagination-centered"><%= will_paginate @dealers %></div>
      <% end %>
    </div>
  </div>
</section>

app/views/dealers/edit.html.erb
<% 
  set_meta_tags title: t("edit_your_profile"),
                keywords: @customKeywords
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2><%= t("edit_your_profile")%></h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
      <div class="large-12 medium-12 columns UserTabs">
	    <ul data-options="deep_linking: true" class="tabs" data-tab>
	      <li class="tab-title active"><a href="#Overview"><%= t("my_information") %></a></li>
	      <li class="tab-title"><a href="#Description"><%= t("my_password") %></a></li>
	    </ul>
	    <div class="tabs-content">
	      <div class="content active clearfix" id="Overview">
	        <%= render 'edit_form' %>
	      </div>
	      <div class="content" id="Description">
	        <%= render 'edit_password_form' %>
	      </div>
	    </div>
	  </div>
  </div>
</section>

app/views/dealers/edit_password.html.erb
<section>
  	<div class="row">
	    <div class="columns large-6 medium-6 medium-centered large-centered">
			<h1>Editing Dealer Password</h1>
			<%= @dealer %>
			<%= render 'edit_password_form' %>

			<%= link_to 'Show', @dealer %> |
			<%= link_to 'Back', dealers_path %>
		</div>
	</div>
</section>

app/views/dealers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dealers</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Gallery name</th>
      <th>Gallery location</th>
      <th>Street name</th>
      <th>Building number</th>
      <th>id</th>
      <th>type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dealers.each do |dealer| %>
      <tr>
        <td><%= dealer.id %></td>
        <td><%= dealer.gallery_name %></td>
        <td><%= dealer.gallery_location %></td>
        <td><%= dealer.street_name %></td>
        <td><%= dealer.building_number %></td>
        <td><%= dealer.user.meta_id %></td>
        <td><%= dealer.user.meta_type %></td>
        <td><%= link_to 'Show', dealer %></td>
        <td><%= link_to 'Edit', edit_dealer_path(dealer) %></td>
        <td><%= link_to 'Destroy', dealer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dealer', new_dealer_path %>

app/views/dealers/new.html.erb
<% 
  set_meta_tags title: t("new_dealer"),
                keywords: @customKeywords
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
      	<div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2><%= t("new_dealer") %></h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
    <div class="columns FormContainer large-12 medium-12 small-12 large-centered medium-centered clearfix">
			<%= render 'form' %>
		</div>
	</div>
</section>

app/views/dealers/show.html.erb
<% 
	set_meta_tags title: @dealer.gallery_name,
                keywords: @customKeywords + "," + @dealer.gallery_name,
                author: @dealer.gallery_name,
                publisher: @dealer.gallery_name
	if(!@dealer_cars.blank?)
	  	set_meta_tags  og: {
  		og:{
	      title:    @dealer.gallery_name,
	      type:     'website',
	      url:      request.original_url,
	      image:    [{
	        _: "http://"+request.domain+@dealer_cars.last.car_images[0].image.url(:large),
	        width: 470,
	        height: 338,
	      }]
	    },
	    twitter: {
	      card:  "photo",
	      image:    {
	        _: "http://"+request.domain+@dealer_cars.last.car_images[0].image.url(:large),
	        width: 470,
	        height: 338,
	      }
	    }
	  }  
	end
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2 class="detailedTitle"><span><%= @dealer.gallery_name %></span></h2>
    </div>
  </div>
</section>
<section class="UserInfoSection">
	<div class="row">
		<div class="large-8 columns car-search">
	      <ul class="ulStyle">
	      <% @dealer_cars.each do |s| %>
	        <li class="carsItem clearfix">
	          <%= link_to (image_tag s.car_images[0].image.url(:medium)), s ,:class => "carimage" %>
	          <ul class="ulStyle infolist">
	            <li class="title"><span><%= get_make(s.car_make) %></span> <span class=""><%= get_model(s.car_model) %></span></li>
	            <li class="desc">
	            <%= truncate(s.description , :length => 200,  :separator => ' ') do
	              link_to t("see_more") ,car_path(s,:anchor => "Description")
	            end %>
	            </li>
	            <li class="info">
	              <span class="mileage"><i class="fa fa-tachometer"></i><%= s.mileage%><%= t("KM") %></span>
	              <span class="year"><%= s.year %></span>
	              <span class="price"><%= s.price %> <%=t("JD")%></span>
	            </li>
	          </ul>
	          <%= link_to(('<i class="fa fa-cog"></i>').html_safe , edit_car_path(s.id),:class => "carEdit") %>
	        </li>
	      <% end %>
	      </ul>
	      <div class="pagerArea pagination-centered">
	        <%= will_paginate @dealer_cars %>  
	      </div>
	    </div>
		<div class="columns large-4 medium-4 UserInfo" >
			<ul class="ulStyle">
				<li class="text-center Title"><%=t("dealer_information")%></li>
				<li>
					<%=t("name")%> :<span><%= @dealer.name %></span>
			  	</li>
			  	<li>
					<%=t("phone_number")%> : <span><%= @dealer.phone_number %></span>
			  	</li>
			  	<li>
					<%=t("mobile_number")%> :<span><%= @dealer.mobile_number %></span>
			  	</li>
			  	<li>
					<%=t("city")%> :<span><%= Dealer::City[@dealer.city.to_s] %></span>
			  	</li>
			  	<li>
					<%=t("street_name")%> :<span><%= @dealer.street_name %></span>
			  	</li>
			  	<li>
					<%=t("building_number")%> : <span><%= @dealer.building_number %></span>
			  	</li>
					
			</ul>
			<p class="locationlabel"><%=t("gallery_location")%> :</p>
			<p class="location"><%= @dealer.gallery_location %></p>
		</div>
		
	</div>
</section>
<section class="latest_offers">
	<div class="row clearfix">         			
    	<h2><%= t("Latest_Cars") %></h2>
        <%= link_to t("View_All_Latest_Added"), cars_path, class: "link_more" %>
	</div>
    <div id="latest_offers">
    	<% @latest_cars.each do |c| %>
            <div class="latest_item">
	            <%= link_to (image_tag c.car_images[0].image.url(:medium)), c %>
	            <%= link_to ("#{get_make(c.car_make)} #{get_model(c.car_model)}"), c %>
            </div>
        <% end %>
    </div>
    <a class="prev" id="latest_offers_prev" href="#"><i class="fa fa-chevron-left fa-lg"></i></a>
    <a class="next" id="latest_offers_next" href="#"><i class="fa fa-chevron-right fa-lg"></i></a>    
</section>