config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :main_sliders
  end

  get 'set_language/english'

  get 'set_language/arabic'

  get 'homepage/index'
  root to: "homepage#index"
  devise_for :users, :skip => [:registrations]
  resources :cars do
    collection do
      get 'admin_car'
      patch 'admin_car_update'
      post "contact_submit" => "cars#contact_submit"
      delete "delete_image/:id" => "cars#delete_image"
    end
  end
  resources :members do
    collection do
      get 'admin_member'
      patch 'admin_member_update'
      patch  'member/edit/password/' => 'members#update_password'
      put  'member/edit/password/' => 'members#update_password'
    end
  end
  resources :dealers do
    collection do
      get 'admin_dealer'
      patch 'admin_dealer_update'
      patch  'dealer/edit/password/' => 'dealers#update_password'
      put  'dealer/edit/password/' => 'dealers#update_password'
    end
  end
  resources :makes, except: :show
  resources :models, except: :show
  resources :comfort_interiors, except: :show
  resources :interior_designs, except: :show
  resources :colors, except: :show
  resources :interior_colors, except: :show
  resources :safety_features, except: :show
  get 'admin', to: 'admin#index'

end

app/models/comfort_interior.rb
class ComfortInterior < ActiveRecord::Base
  has_many :car_comfort_interiors
  has_many :cars, through: :car_comfort_interiors
  validates :title, presence: true
  translates :title
  globalize_accessors :locales => [:en ,:ar], :attributes => [:title]
  def cache_key
	  super + '-' + Globalize.locale.to_s
	end
end

app/controllers/comfort_interiors_controller.rb
class ComfortInteriorsController < ApplicationController
  before_action :set_comfort_interior, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /comfort_interiors
  # GET /comfort_interiors.json
  def index
    @comfort_interiors = ComfortInterior.all
  end

  # GET /comfort_interiors/1
  # GET /comfort_interiors/1.json
  def show
  end

  # GET /comfort_interiors/new
  def new
    @comfort_interior = ComfortInterior.new
  end

  # GET /comfort_interiors/1/edit
  def edit
  end

  # POST /comfort_interiors
  # POST /comfort_interiors.json
  def create
    @comfort_interior = ComfortInterior.new(comfort_interior_params)

    respond_to do |format|
      if @comfort_interior.save
        format.html { redirect_to comfort_interiors_path, notice: 'Comfort interior was successfully created.' }
        format.json { render :show, status: :created, location: @comfort_interior }
      else
        format.html { render :new }
        format.json { render json: @comfort_interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comfort_interiors/1
  # PATCH/PUT /comfort_interiors/1.json
  def update
    respond_to do |format|
      if @comfort_interior.update(comfort_interior_params)
        format.html { redirect_to comfort_interiors_path, notice: 'Comfort interior was successfully updated.' }
        format.json { render :show, status: :ok, location: @comfort_interior }
      else
        format.html { render :edit }
        format.json { render json: @comfort_interior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comfort_interiors/1
  # DELETE /comfort_interiors/1.json
  def destroy
    @comfort_interior.destroy
    respond_to do |format|
      format.html { redirect_to comfort_interiors_url, notice: 'Comfort interior was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comfort_interior
      @comfort_interior = ComfortInterior.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comfort_interior_params
      params.require(:comfort_interior).permit(:title,ComfortInterior.globalize_attribute_names)
    end
end

app/helpers/comfort_interiors_helper.rb
module ComfortInteriorsHelper
end

app/views/comfort_interiors/_form.html.erb
<%= form_for(@comfort_interior) do |f| %>
  <% if @comfort_interior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comfort_interior.errors.count, "error") %> prohibited this comfort_interior from being saved:</h2>

      <ul>
      <% @comfort_interior.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title_ar, "Arabic Title" %><br>
    <%= f.text_field :title_ar %>
  </div>
  <div class="field">
    <%= f.label :title_en, "English Title" %><br>
    <%= f.text_field :title_en %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comfort_interiors/edit.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>Editing Comfort Interior</h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
    <div class="large-12 medium-12 columns UserTabs">
    	<%= render 'form' %>
	  </div>
  </div>
</section>

app/views/comfort_interiors/index.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>Listing Comfort Interior</h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
    <div class="large-12 medium-12 columns UserTabs">
      <table>
        <thead>
          <tr>
            <th>Title English</th>
            <th>Title Arabic</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @comfort_interiors.each do |comfort_interior| %>
            <tr>
              <td><%= comfort_interior.title_en %></td>
              <td><%= comfort_interior.title_ar %></td>
              <td><%= link_to 'Edit', edit_comfort_interior_path(comfort_interior) %></td>
              <td><%= link_to 'Destroy', comfort_interior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to 'New Comfort interior', new_comfort_interior_path %>
    </div>
  </div>
</section>

app/views/comfort_interiors/new.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>New Comfort Interior</h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
    <div class="large-12 medium-12 columns UserTabs">
    	<%= render 'form' %>
	  </div>
  </div>
</section>

app/views/comfort_interiors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comfort_interior.title %>
</p>

<%= link_to 'Edit', edit_comfort_interior_path(@comfort_interior) %> |
<%= link_to 'Back', comfort_interiors_path %>