config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :main_sliders
  end

  get 'set_language/english'

  get 'set_language/arabic'

  get 'homepage/index'
  root to: "homepage#index"
  devise_for :users, :skip => [:registrations]
  resources :cars do
    collection do
      get 'admin_car'
      patch 'admin_car_update'
      post "contact_submit" => "cars#contact_submit"
      delete "delete_image/:id" => "cars#delete_image"
    end
  end
  resources :members do
    collection do
      get 'admin_member'
      patch 'admin_member_update'
      patch  'member/edit/password/' => 'members#update_password'
      put  'member/edit/password/' => 'members#update_password'
    end
  end
  resources :dealers do
    collection do
      get 'admin_dealer'
      patch 'admin_dealer_update'
      patch  'dealer/edit/password/' => 'dealers#update_password'
      put  'dealer/edit/password/' => 'dealers#update_password'
    end
  end
  resources :makes, except: :show
  resources :models, except: :show
  resources :comfort_interiors, except: :show
  resources :interior_designs, except: :show
  resources :colors, except: :show
  resources :interior_colors, except: :show
  resources :safety_features, except: :show
  get 'admin', to: 'admin#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :car_safety_features, dependent: :destroy
  has_many :safety_features, through: :car_safety_features
  has_many :car_comfort_interiors, dependent: :destroy
  has_many :comfort_interiors, through: :car_comfort_interiors
  has_many :car_images, dependent: :destroy
  has_one :color
  has_one :interior_color
  has_one :interior_design
  has_one :make
  has_one :model
  belongs_to :user
  validates :title, :car_make, :car_model, :year, :car_location, :contact_number, :gearbox_id, :color_id, :interior_design_id, :report, :car_images, presence: true
  validates :report_other, presence: true, if: :report_other?
  validates :car_images, length: { in: 1..12 }
  accepts_nested_attributes_for :car_images, :reject_if => :all_blank, :allow_destroy => true
  Gearbox = {"1" => "manual", "2" => "automatic"}
  FUELTYPE = {"1" => "petrol", "2" => "diesel", "3" => "hybrid"}
  REPORT = {"1" => "accident_free", "2" => "damaged", "3" => "repaired", "4" => "other"}
  City = {
  "1" => "Amman",
  "2" => "Zarqa",
  "3" => "Irbid",
  "4" => "Aqaba",
  "5" => "as-Salt",
  "6" => "Ar Ramtha",
  "7" => "Madaba",
  "8" => "Mafraq",
  "9" => "Jerash",
  "10" => "Ma'an",
  "11" => "Tafilah",
  "12" => "Karak",
  "13" => "Ajloun"
}
  def report_other?
    report === 4
  end
  searchable do
    integer :car_make
    integer :car_model
    integer :cubic_capacity
    integer  :year
    integer :mileage
    integer :gearbox_id
    integer :fuel_type
    integer :color_id
    integer :report
    integer :price
    date :created_at
    integer :comfort_interior_ids, multiple: true do
      comfort_interiors.map(&:id)
    end
    integer :safety_feature_ids, multiple: true do
      safety_features.map(&:id)
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :authenticate_access!, :only => [:edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    if params[:q]

      if params[:q][:sort]
        case params[:q][:sort]
        when "1"
          column = "created_at"
          type = "desc"
        when "2"
          column = "created_at"
          type = "asc"
        when "3"
          column = "price"
          type = "desc"
        when "4"
          column = "price"
          type = "asc"
        when "5"
          column = "year"
          type = "desc"
        when "6"
          column = "year"
          type = "desc"
        end
      else
        column = "created_at"
        type = "desc"
      end
      @search = Car.search do
        with(:car_make).equal_to(params[:q][:car_make]) if params[:q][:car_make].present?
        with(:car_model).equal_to(params[:q][:car_model]) if params[:q][:car_model].present?
        with(:cubic_capacity).greater_than_or_equal_to(params[:q][:cubic_capacity_from].to_i) if params[:q][:cubic_capacity_from].present?
        with(:cubic_capacity).less_than_or_equal_to(params[:q][:cubic_capacity_to].to_i) if params[:q][:cubic_capacity_to].present?
        with(:year).greater_than_or_equal_to(params[:q][:year_from].to_i) if params[:q][:year_from].present?
        with(:year).less_than_or_equal_to(params[:q][:year_to].to_i) if params[:q][:year_to].present?
        with(:price).greater_than_or_equal_to(params[:q][:price_from].to_i) if params[:q][:price_from].present?
        with(:price).less_than_or_equal_to(params[:q][:price_to].to_i) if params[:q][:price_to].present?
        with(:gearbox_id).equal_to(params[:q][:gearbox_id]) if params[:q][:gearbox_id].present?
        with(:fuel_type).equal_to(params[:q][:fuel_type]) if params[:q][:fuel_type].present?
        with(:color_id).equal_to(params[:q][:color_id]) if params[:q][:color_id].present?
        with(:report).equal_to(params[:q][:report]) if params[:q][:report].present?
        with(:comfort_interior_ids).all_of(params[:q][:comfort_interior_ids]) if params[:q][:comfort_interior_ids].present?
        with(:safety_feature_ids).all_of(params[:q][:safety_feature_ids]) if params[:q][:safety_feature_ids].present?
        order_by column, type
        paginate :page => params[:page] || 1, :per_page => 50
      end
      @cars = @search.results
    else
      @cars = Car.all.page(params[:page]).per_page(50)
    end
    @special_cars = Car.where(special_car: true)
    @latest_cars = Car.last(50)
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @user = User.find(@car.user_id)
    @latest_cars = Car.last(10)
    if(@user.meta_type == "Dealer")
      @page_author = request.original_url + dealer_path(@user.meta_id)
      @page_publisher = request.original_url + dealer_path(@user.meta_id)
    else
      @page_author = request.original_url + member_path(@user.meta_id)
      @page_publisher = request.original_url + member_path(@user.meta_id)
    end
  end

  # GET /cars/new
  def new
    @car = Car.new
    if current_user.meta_type == "Member"
      5.times { @car.car_images.build }
    end
    if current_user.meta_type == "Dealer"
      12.times { @car.car_images.build }
    end

  end

  # GET /cars/1/edit
  def edit
    if current_user.meta_type == "Dealer"
        image_count = @car.car_images.size
        image_count = 12-image_count
        image_count.times { @car.car_images.build }
    end
    if current_user.meta_type == "Member"
        image_count = @car.car_images.size
        image_count = 5-image_count
        image_count.times { @car.car_images.build }
    end
    @latest_cars = Car.last(10)
  end

  # POST /cars
  # POST /cars.json
  def create
    car_params.delete(:special_car) unless current_user.isadmin
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        if current_user.meta_type == "Dealer"
            image_count = @car.car_images.size
            image_count = 12-image_count
            image_count.times { @car.car_images.build }
        end
        if current_user.meta_type == "Member"
            image_count = @car.car_images.size
            image_count = 5-image_count
            image_count.times { @car.car_images.build }
        end
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    car_params.delete(:special_car) unless current_user.isadmin
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contact_submit
    @car = Car.find(params[:carId])
    ContactMailer.contact_email(params[:senderName], params[:senderEmail], params[:senderMessage], Car.find(params[:carId]), User.find(params[:ownerId])).deliver_now
    redirect_to @car, notice: 'Car was successfully created.'
  end
  def admin_car
    @cars = Car.includes(:user).all.page(params[:page]).per_page(50)
  end
  def admin_car_update
    params['car'].keys.each do |id|
      @car = Car.find(id.to_i)
      @car.update_attributes(admin_car_params(id))
    end
    redirect_to(admin_car_cars_path)
  end
  def delete_image
    image = CarImage.find(params[:id]).destroy
    redirect_to edit_car_path(image.car_id)+"#Description"
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:sort,:remove_image,:title, :description, :year, :mileage, :price, :car_location, :contact_number, :report, :report_other, :gearbox_id, :color_id, :car_make, :car_model, :interior_design_id, :fuel_type, :cubic_capacity, :special_car, :interior_color_id, :city, :safety_feature_ids => [], :comfort_interior_ids => [], car_images_attributes: [:id, :image, :_destroy, :image_cache])
    end
    def admin_car_params(id)
      params.require(:car).fetch(id).permit(:special_car)
    end
    def authenticate_access!
      if user_signed_in?
        if(current_user.id == Car.find(params[:id]).user_id || current_user.isadmin)
          true
        else
          redirect_to @car
        end
      else
        redirect_to @car
      end
    end
end

app/helpers/cars_helper.rb
module CarsHelper
	def get_safety_feature_title (id)
    @safety_feature = SafetyFeature.find(id).title
  end

  def get_comfort_interior_title (id)
    @comfort_interior = ComfortInterior.find(id).title
  end

  def get_color (id)
    @make = Color.find(id).title
  end

  def get_interior_design (id)
    @make = InteriorDesign.find(id).title
  end

  def get_interior_color (id)
		if(id)
    	@make = InteriorColor.find(id).title
		end
  end

end

app/views/cars/_car_detailed_info.html.erb
<section id="FormCarDetail">
  <div class="medium-8 columns">
    <div class="field clearfix">
      <%= f.label t("Comfort_and_Interior_Design") %>
      <%= f.collection_check_boxes :comfort_interior_ids, ComfortInterior.all, :id, :title, include_hidden: false do |cb| %>
        <% cb.label(class: "checkbox inline") {cb.check_box(class:"checkbox") + cb.text} %>
      <% end %>
    </div>
    <div class="field clearfix">
      <%= f.label t("Safety_Features") %>
      <%= f.collection_check_boxes :safety_feature_ids, SafetyFeature.all, :id, :title, include_hidden: false do |cb2| %>
        <% cb2.label(class: "checkbox inline") {cb2.check_box(class:"checkbox") + cb2.text} %>
      <% end %>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <div class="field">
      <%= f.label :contact_number, t("Phone_Number") %>
      <%= f.text_field :contact_number %>
    </div>
    <div>
      <%= f.label t("city") %>
      <%= f.select :city, Car::City.map{ |s| [s[1] , s[0]] } %>
    </div>
    <div class="field">
      <%= f.label :car_location, t("Car_location") %>
      <%= f.text_area :car_location %>
    </div>
    <% if current_user.isadmin %>
      <div class="field">
        <%= f.label :special_car %>
        <%= f.check_box :special_car %>
      </div>
    <% end %>
  </div>
</section>

app/views/cars/_car_image_upload.html.erb
<section id="FormCarImage" class="clearfix">
	<div class="columns medium-8">
		<div class="file_field">
			<%= f.fields_for :car_images do |image| %>
				<div class="nested-fields">
					<div class="inputimagecontainer th">
						<%= image.file_field :image , animated: false, class: "myfile" %>
						<% if(image.object.image_url.blank?) %>
							<%= image_tag("CarIcon#{image.index}.png", size: "250x52") %>
						<% else %>
							<%= image_tag(image.object.image_url, size:"250x52") %>
						<% end %>
					</div>
					<%= image.hidden_field :image_cache %>
					<% unless (image.object.id.blank?) %>
  						<%= link_to "remove" , "/cars/delete_image/#{image.object.id}", method: :delete %>
  					<% end %>
				
				</div>
			<% end %>
		</div>
	</div>
  <div class="field columns medium-4">
    <%= f.label t(:color) %>
    <%= collection_select(:car, :color_id, Color.all, :id, :title) %>
  </div>
  <div class="field columns medium-4">
    <%= f.label :interior_design, t("Interior_Design") %>
    <%= collection_select(:car, :interior_design_id, InteriorDesign.all, :id, :title) %>
  </div>
	<div class="field columns medium-4">
    <%= f.label :interior_color,t("Interior_Color") %>
    <%= collection_select(:car, :interior_color_id, InteriorColor.all, :id, :title) %>
  </div>
	<div class="field columns medium-12">
      <%= f.label :description, t("Description") %>
      <%= f.text_area :description, :rows => "3"%>
  </div>
</section>

app/views/cars/_edit_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>
      <ul>
        <% @car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="large-12 medium-12 columns CarDetailTabs">
    <ul data-options="deep_linking: true" class="tabs" data-tab>
      <li class="tab-title active"><a href="#Overview"><%= t("car_information") %></a></li>
      <li class="tab-title"><a href="#Description"><%= t("Car_Images_Appearance") %></a></li>
      <li class="tab-title"><a href="#Contact"><%= t("Features_Contact_Information") %></a></li>
    </ul>
    <div class="tabs-content">
      <div class="content active clearfix" id="Overview">
        <%= render 'car_main_info', :f => f %>
      </div>
      <div class="content" id="Description">
        <%= render 'car_image_upload', :f => f %>
      </div>
      <div class="content clearfix" id="Contact">
        <%= render 'car_detailed_info', :f => f %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit "Update Car", :class => 'button tiny buttoncustom' %>
    </div>
  </div>
<% end %>

app/views/cars/admin_car.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>Cars Admin Page</h2>
    </div>
  </div>
</section>
<section class="NewCar">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
    	<%= form_for :car, :url => admin_car_update_cars_path, :html => { :method => :patch } do %>
		    <table>
		    	<thead>
				    <tr>
				      <th>Title</th>
				      <th>Type</th>
				      <th>User</th>
				      <th>User Type</th>
				      <th>Created At</th>
				      <th>Updated At</th>
				      <th>Special Cars</th>
				      <th colspan="7"></th>
				    </tr>
		  		</thead>
				  <tbody>
				    <% @cars.each do |car| %>
				      <tr>
				        <td><%= car.title %></td>
				        <td><%= get_make(car.car_make) %> <%= get_model(car.car_model) %></td>
				        <td><% unless car.user.blank? %><%= car.user.email %><%end%></td>
				        <td><% unless car.user.blank? %><%= car.user.meta_type %><%end%></td>
				        <td><%= car.created_at %></td>
				        <td><%= car.updated_at %></td>
				        <%= fields_for "car[]", car do |f| %>
					      	<td><%= f.check_box :special_car %></td>
					      <% end %>
				        <td><%= link_to 'Show', car %></td>
				        <td><%= link_to 'Edit', edit_car_path(car) %></td>
				        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				      </tr>
				    <% end %>
		  		</tbody>
				</table>
				<div class="actions">
			    <%= submit_tag %>
			  </div>
		  <% end %>
      <% if !(@cars.total_pages == 1) %>
        <div class="pagerArea pagination-centered"><%= will_paginate @cars %></div>
      <% end %>
    </div>
  </div>
</section>

app/views/cars/edit.html.erb
<%
  set_meta_tags title: t('editing_car'),
                keywords: @customKeywords
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2><%=t("editing_car")%></h2>
    </div>
  </div>
</section>
<section class="EditCar">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
		<%= render 'edit_form' %>
    </div>
  </div>
</section>
<section class="latest_offers">
  <div class="row clearfix">
      <h2><%= t("Latest_Cars") %></h2>
        <%= link_to t("View_All_Latest_Added"), cars_path, class: "link_more" %>
  </div>
    <div id="latest_offers">
      <% @latest_cars.each do |c| %>
            <div class="latest_item">
              <% unless c.car_images[0].blank? %>
              <%= link_to (image_tag c.car_images[0].image.url(:medium)), c %>
              <% end %>
              <%= link_to ("#{get_make(c.car_make)} #{get_model(c.car_model)}"), c %>
            </div>
        <% end %>
    </div>
    <a class="prev" id="latest_offers_prev" href="#"><i class="fa fa-chevron-left fa-lg"></i></a>
    <a class="next" id="latest_offers_next" href="#"><i class="fa fa-chevron-right fa-lg"></i></a>
</section>

app/views/cars/index.html.erb
<%
  set_meta_tags title: t('Search'),
                keywords: @customKeywords + ",البحث عن سيارات"
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="searcharea">
  <div class="row">
    <div class="small-12 columns">
      <div class="carSearchSideBar">
        <%= form_tag cars_path, :id => 'car_search_form', :method => :get do %>
          <div class="large-3 medium-3 columns">
            <%= label_tag t(:car_make) %>
            <%= select_tag 'q[car_make]', options_for_select(Make.all.with_translations(I18n.locale).order('title').map{ |c| [c.title, c.id] }), include_blank: t("all") %>
          </div>
          <div id="HomeSearchModel" class="formCarModel large-3 medium-3 columns">
            <%= label_tag t(:car_model) %>
            <%= select_tag 'q[car_model]', options_for_select(Model.all.with_translations(I18n.locale).order("title").map{ |c| [c.title, c.id, {'parent_id'=>c.parent_id}] }), include_blank: t("all"), disabled: true%>
          </div>
          <div class="large-3 medium-3 columns">
            <%= label_tag t(:year_from) %>
            <%= select_tag 'q[year_from]', options_for_select(((Time.zone.now.year - 70)..(Time.zone.now.year + 1)).to_a.reverse), include_blank: t("all") %>
          </div>
          <div class="large-3 medium-3 columns">
            <%= label_tag t(:year_to) %>
            <%= select_tag 'q[year_to]', options_for_select(((Time.zone.now.year - 70)..(Time.zone.now.year + 1)).to_a.reverse), include_blank: t("all") %>
          </div>
          <a id="advancedSearchToggleOn" href="javascript:void(0);"><%= t("advanced_search") %></a>
          <div id="advancedSearch" class="clearfix">
            <div class="large-3 medium-3 columns">
              <%= label_tag t(:price_from) %>
              <%= select_tag 'q[price_from]' , options_for_select((0..300000).step(1000)), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t(:price_to) %>
              <%= select_tag 'q[price_to]' , options_for_select((0..300000).step(1000)), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t("Gear_Box_Type") %>
              <%= select_tag 'q[gearbox_id]', options_for_select(Car::Gearbox.map{ |s| [I18n.t(s[1]) , s[0]] }), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t(:cubic_capacity_from) %>
              <%= select_tag 'q[cubic_capacity_from]' , options_for_select([1000,1200,1600,1800,2000,2600,3000,5000,7500,8000,9000]), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t(:cubic_capacity_to) %>
              <%= select_tag 'q[cubic_capacity_to]' , options_for_select([1000,1200,1600,1800,2000,2600,3000,5000,7500,8000,9000]), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t(:fuel_type) %>
              <%= select_tag 'q[fuel_type]' , options_for_select(Car::FUELTYPE.map{ |s| [I18n.t(s[1]) , s[0]] }), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t("color") %>
              <%= select_tag 'q[color_id]', options_for_select(Color.all.map{ |c| [c.title, c.id]}), include_blank: t("all") %>
            </div>
            <div class="large-3 medium-3 columns">
              <%= label_tag t("Car_Report") %>
              <%= select_tag 'q[report]', options_for_select(Car::REPORT.map{ |s| [I18n.t(s[1]) , s[0]] }), include_blank: t("all") %>
            </div>
            <div class="large-12 medium-12 columns">
              <%= label_tag t("Comfort_and_Interior_Design") %>
              <% ComfortInterior.all.each do |v| %>
                <span class="search-checkbox">
                  <%= check_box_tag 'q[comfort_interior_ids][]', v.id, false  %>
                  <%= v.title %>
                </span>
              <% end %>
            </div>
            <div class="large-12 medium-12 columns">
              <%= label_tag t("Safety_Features") %>
              <% SafetyFeature.all.each do |v| %>
                <span class="search-checkbox">
                  <%= check_box_tag 'q[safety_feature_ids][]', v.id, false  %>
                  <%= v.title %>
                </span>
              <% end %>
            </div>
          </div>
          <a id="advancedSearchToggleOff" href="javascript:void(0);"><%= t("advanced_search_hide") %></a>
          <div class="actions text-right large-12 medium-12 columns">
              <%= submit_tag t("Search"), class: "button tiny radius" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<section class="searchResults">
  <div class="row">
    <div class="large-10 columns car-search small-8">
      <% if(@cars) %>
      <select id="searchSort">
        <option value="1">Date new to old</option>
        <option value="2">Date old to new</option>
        <option value="3">Price highest to lowest</option>
        <option value="4">Price lowest to highest</option>
        <option value="5">Year new to old</option>
        <option value="6">Year old to new</option>
      </select>
      <ul class="ulStyle">
        <% @cars.each do |s| %>
          <li class="carsItem clearfix">
            <%= link_to (image_tag s.car_images[0].image.url(:medium)), s ,:class => "carimage" %>
            <ul class="ulStyle infolist">
              <li class="title"><span><%= get_make(s.car_make) %></span> <span class=""><%= get_model(s.car_model) %></span></li>
              <li class="desc">
              <%= truncate(s.description , :length => 200,  :separator => ' ') do
                link_to "see more..." ,car_path(s,:anchor => "Description")
              end %>
              </li>
              <li class="info">
                <span class="mileage"><i class="fa fa-tachometer"></i><%= s.mileage %> <%=t("KM")%></span>
                <span class="year"><%= s.year %></span>
                <span class="price"><%= s.price %> <%=t("JD")%></span>
              </li>

            </ul>
          </li>
        <% end %>
        </ul>
      <% else %>
        <li class="noResults"><%= t('no_results') %></li>
      <% end %>

      <% if !(@cars.total_pages == 1) %>
        <div class="pagerArea pagination-centered">
          <%= will_paginate @cars %>
        </div>
      <% end %>
    </div>
    <div class="large-2 columns small-4">
      <div class="specialCarSideBar">
        <ul class="ulStyle">
        <% @special_cars.each do |s| %>
          <li>
            <%= link_to (image_tag s.car_images[0].image.url(:small)), s ,:class => "inlineBlockImage" %>
          </li>
          <li><%= s.year %></li>

        <% end %>
        </ul>
      </div>
    </div>
  </div>
</section>
<section class="latest_offers">
  <div class="row clearfix">
      <h2><%= t("Latest_Cars") %></h2>
        <%= link_to t("View_All_Latest_Added"), cars_path, class: "link_more" %>
  </div>
    <div id="latest_offers">
      <% @latest_cars.each do |c| %>
            <div class="latest_item">
              <%= link_to (image_tag c.car_images[0].image.url(:medium)), c %>
              <%= link_to ("#{get_make(c.car_make)} #{get_model(c.car_model)}"), c %>
            </div>
        <% end %>
    </div>
    <a class="prev" id="latest_offers_prev" href="#"><i class="fa fa-chevron-left fa-lg"></i></a>
    <a class="next" id="latest_offers_next" href="#"><i class="fa fa-chevron-right fa-lg"></i></a>
</section>