config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :main_sliders
  end

  get 'set_language/english'

  get 'set_language/arabic'

  get 'homepage/index'
  root to: "homepage#index"
  devise_for :users, :skip => [:registrations]
  resources :cars do
    collection do
      get 'admin_car'
      patch 'admin_car_update'
      post "contact_submit" => "cars#contact_submit"
      delete "delete_image/:id" => "cars#delete_image"
    end
  end
  resources :members do
    collection do
      get 'admin_member'
      patch 'admin_member_update'
      patch  'member/edit/password/' => 'members#update_password'
      put  'member/edit/password/' => 'members#update_password'
    end
  end
  resources :dealers do
    collection do
      get 'admin_dealer'
      patch 'admin_dealer_update'
      patch  'dealer/edit/password/' => 'dealers#update_password'
      put  'dealer/edit/password/' => 'dealers#update_password'
    end
  end
  resources :makes, except: :show
  resources :models, except: :show
  resources :comfort_interiors, except: :show
  resources :interior_designs, except: :show
  resources :colors, except: :show
  resources :interior_colors, except: :show
  resources :safety_features, except: :show
  get 'admin', to: 'admin#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	has_one :user, as: :meta, dependent: :destroy
	validates :first_name, :last_name, :phone_number, :address, presence: true
  	accepts_nested_attributes_for :user
  	City = {
		"1" => "Amman",
		"2" => "Zarqa",
		"3" => "Irbid",
		"4" => "Aqaba",
		"5" => "as-Salt",
		"6" => "Ar Ramtha",
		"7" => "Madaba",
		"8" => "Mafraq",
		"9" => "Jerash",
		"10" => "Ma'an",
		"11" => "Tafilah",
		"12" => "Karak",
		"13" => "Ajloun"
	}
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :set_user , only: [:update_password, :edit]
  before_action :authenticate_access!, :only => [:index ,:edit, :update]
  before_action :authenticate_admin!,:only =>[:admin_member ,:index, :destroy]
  
  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member_cars = Car.where(user_id: @member.user.id).order('created_at DESC').page(params[:page]).per_page(10)
    @latest_cars = Car.last(10)
  end

  # GET /members/new
  def new
    @member = Member.new
    @member.build_user
  end

  # GET /members/1/edit
  def edit
  end
  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/edit/password
  # PATCH/PUT 
  def update_password
    respond_to do |format|
      if @user.update(member_params)
        format.html { redirect_to @user, notice: 'Member Password was successfully updated. Please login again' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit_password }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to admin_member_members_path, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def admin_member
    @members = Member.includes(:user).all.page(params[:page]).per_page(50)
  end
  def admin_member_update
    params['user'].keys.each do |id|
      @user = User.find(id.to_i)
      @user.update_attributes(admin_user_params(id))
    end
    if(authenticate_admin?)
      redirect_to(admin_member_members_path)
    else
      redirect_to root_path
    end
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end
    def set_user
      user = User.find(current_user.id)
      @user = Member.find(user.meta_id)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:page ,:first_name, :last_name, :phone_number, :address, user_attributes: [ :id, :email, :password, :password_confirmation ])
    end
    def admin_user_params(id)
      params.require(:user).fetch(id).permit(:isadmin)
    end
    def authenticate_access!
      if user_signed_in?
        if(current_user.meta_id == Member.find(params[:id]).id || current_user.isadmin)
          true
        else
          if(@member)
            redirect_to @member
          else
            redirect_to :root
          end
        end
      else
        if(@member)
            redirect_to @member
          else
            redirect_to :root
          end
      end
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_edit_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label t(:first_name) %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label  t(:last_name) %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label t(:phone_number) %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label t(:address) %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions text-center">
    <%= f.submit t("update_information"), :class => 'button tiny buttoncustom' %>
  </div>
<% end %>

app/views/members/_edit_password_form.html.erb
<%= form_for @user , :url => url_for(:controller => 'members', :action => 'update_password') do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :user do |u| %>
    <div class="col-lg-6">
      <%= u.label t(:password) %><br>
      <%= u.password_field :password %>
    </div>
    
    <div class="col-lg-6">
      <%= u.label t(:password_confirmation) %><br>
      <%= u.password_field :password_confirmation %>
    </div>
  <% end %>
  <div class="actions text-center">
    <%= f.submit t("update_password"), :class => 'button tiny buttoncustom' %>
  </div>
<% end %>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div data-alert class="alert-box warning">
      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="userInfo large-6 columns">
    <div class="field">
      <%= f.label t(:first_name) %>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label t(:last_name) %>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label t(:phone_number) %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="field">
      <%= f.label t(:address)%>
      <%= f.text_area :address %>
    </div>
  </div>
  <div class="userLoginInfo large-6 columns">
    <div class="innerUserLoginInfo">
      <%= f.fields_for :user do |u| %>
        <div class="col-lg-6">      
          <%= u.label t(:email) %>
          <%= u.text_field :email %>
        </div>
        
        <div class="col-lg-6">
          <%= u.label t(:password) %>
          <%= u.password_field :password %>
        </div>
        
        <div class="col-lg-6">
          <%= u.label t(:password_confirmation) %>
          <%= u.password_field :password_confirmation %>
        </div>    
      <% end %>
      <div class="actions text-center">
        <%= f.submit t("sign_in"), :class => 'button tiny buttoncustom createCar' %>
      </div>
    </div>
  </div>
  
<% end %>

app/views/members/admin_member.html.erb
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2>Dealers Admin Page</h2>
    </div>
  </div>
</section>
<section class="NewCar">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
    	<%= form_for :member, :url => admin_member_update_members_path, :html => { :method => :patch } do %>
		    <table>
		    	<thead>
				    <tr>
				      <th>Email</th>
				      <th>First Name</th>
				      <th>Last Name</th>
				      <th>Last Sign In</th>
				      <th>Created At</th>
				      <th>Admin</th>
				      <th colspan="2"></th>
				    </tr>
		  		</thead>
				  <tbody>
				    <% @members.each do |member| %>
				      <tr>
				        <td><%= member.user.email %></td>
				        <td><%= member.first_name %></td>
				        <td><%= member.last_name %></td>
				        <td><%= member.user.last_sign_in_at %></td>
				        <td><%= member.created_at %></td>
				        <%= fields_for "user[]", member.user do |f| %>
					      	<td><%= f.check_box :isadmin %></td>
					      <% end %>
				        <td><%= link_to 'Show', member %></td>
				        <td><%= link_to 'Edit', edit_member_path(member) %></td>
				        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				      </tr>
				    <% end %>
		  		</tbody>
				</table>
				<div class="actions">
			    <%= submit_tag %>
			  </div>
		  <% end %>
      <% if !(@members.total_pages == 1) %>
        <div class="pagerArea pagination-centered"><%= will_paginate @members %></div>
      <% end %>
    </div>
  </div>
</section>

app/views/members/edit.html.erb
<% 
  set_meta_tags title: t("edit_your_profile"),
                keywords: @customKeywords
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2><%= t("edit_your_profile")%></h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
      <div class="large-12 medium-12 columns UserTabs">
	    <ul data-options="deep_linking: true" class="tabs" data-tab>
	      <li class="tab-title active"><a href="#Overview"><%= t("my_information")%></a></li>
	      <li class="tab-title"><a href="#Description"><%=t("my_password")%></a></li>
	    </ul>
	    <div class="tabs-content">
	      <div class="content active clearfix" id="Overview">
	        <%= render 'edit_form' %>
	      </div>
	      <div class="content" id="Description">
	        <%= render 'edit_password_form' %>
	      </div>
	    </div>
	  </div>
  </div>
</section>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Address</th>
      <th>id</th>
      <th>meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.phone_number %></td>
        <td><%= member.address %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<% 
  set_meta_tags title: t("new_member"),
                keywords: @customKeywords
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
        <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2><%= t("new_member") %></h2>
    </div>
  </div>
</section>
<section class="DeviseForms">
  <div class="row">
    <div class="columns FormContainer large-12 medium-12 small-12 large-centered medium-centered clearfix">
      <%= render 'form' %>
    </div>
  </div>
</section>

app/views/members/show.html.erb
<%
  set_meta_tags title: @member.first_name+ " " + @member.last_name,
                keywords: @customKeywords + "," + @member.first_name + "," + @member.last_name,
                author: @member.first_name+ " " + @member.last_name,
                publisher: @member.first_name+ " " + @member.last_name
    if(!@member_cars.blank?)
	  	set_meta_tags  og: {
        og: {
          title:    @member.first_name+ " " + @member.last_name,
          type:     'website',
          url:      request.original_url,
          image:    [{
            _: "http://"+request.domain+@member_cars.last.car_images[0].image.url(:large),
            width: 470,
            height: 338,
          }]
        },
        twitter: {
          card:  "photo",
          image:    {
            _: "http://"+request.domain+@member_cars.last.car_images[0].image.url(:large),
            width: 470,
            height: 338,
          }
        }
      }
    end
%>
<section class="PageHead">
  <div class="AdContainer">
    <div class="row">
      <div class="columns large-12 medium-12 medium-centered large-centered">
          <div class="AdArea">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- ????? -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-9051649943133421"
                 data-ad-slot="1612164192"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>
      </div>
    </div>
  </div>
</section>
<section class="PageTitle">
  <div class="row">
    <div class="columns large-12 medium-12 medium-centered large-centered">
      <h2 class="detailedTitle"><span><%= @member.first_name %> <%= @member.last_name %></span></h2>
    </div>
  </div>
</section>
<section class="UserInfoSection">
	<div class="row">
		<div class="large-8 columns car-search">
	      <ul class="ulStyle">
	      <% @member_cars.each do |s| %>
	        <li class="carsItem clearfix">
	          <%= link_to (image_tag s.car_images[0].image.url(:medium)), s ,:class => "carimage" %>
	          <ul class="ulStyle infolist">
	            <li class="title"><span><%= get_make(s.car_make) %></span> <span class=""><%= get_model(s.car_model) %></span></li>
	            <li class="desc">
	            <%= truncate(s.description , :length => 200,  :separator => ' ') do
	              link_to "see more..." ,car_path(s,:anchor => "Description")
	            end %>
	            </li>
	            <li class="info">
	              <span class="mileage"><i class="fa fa-tachometer"></i><%= s.mileage %> <%=t("KM")%></span>
	              <span class="year"><%= s.year %></span>
	              <span class="price"><%= s.price %> <%=t("JD")%></span>
	            </li>
	          </ul>
            <% if (current_user == @member.user) %>
              <%= link_to(('<i class="fa fa-cog"></i>').html_safe , edit_car_path(s),:class => "carEdit") %>
              <%= link_to(('<i class="fa fa-trash"></i>').html_safe ,car_path(s), method: :delete, data: { confirm: 'Are you sure?' },:class => "carDestroy") %>
            <%end%>
	        </li>
	      <% end %>
	      </ul>
	      <div class="pagerArea pagination-centered">
	        <%= will_paginate @member_cars %>
	      </div>
	    </div>
		<div class="columns large-4 medium-4 UserInfo" >
			<ul class="ulStyle">
				<li class="text-center Title"><%=t("member_information")%></li>
				<li>
					<%=t("name")%> :<span><%= @member.first_name %> <%= @member.last_name %></span>
			  	</li>
			  	<li>
					<%=t("phone_number")%> : <span><%= @member.phone_number %></span>
			  	</li>
			</ul>
			<p class="locationlabel"><%=t("Car_location")%> :</p>
			<p class="location"><%= @member.address %></p>
		</div>
	</div>
</section>
<section class="latest_offers">
	<div class="row clearfix">
    	<h2><%= t("Latest_Cars") %></h2>
        <%= link_to t("View_All_Latest_Added"), cars_path, class: "link_more" %>
	</div>
    <div id="latest_offers">
    	<% @latest_cars.each do |c| %>
            <div class="latest_item">
	            <%= link_to (image_tag c.car_images[0].image.url(:medium)), c %>
	            <%= link_to ("#{get_make(c.car_make)} #{get_model(c.car_model)}"), c %>
            </div>
        <% end %>
    </div>
    <a class="prev" id="latest_offers_prev" href="#"><i class="fa fa-chevron-left fa-lg"></i></a>
    <a class="next" id="latest_offers_next" href="#"><i class="fa fa-chevron-right fa-lg"></i></a>
</section>